name: Flask App CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests (Optional, you can add tests in the future)
      run: |
        # If you add tests later
        echo "No tests yet, skipping test step"

    - name: Deploy to Server (or other actions)
      run: |
        echo "Deploying the Flask app to your server or any platform"

